### ISSUE TITLE
Revert description text to have one leading space

### ISSUE THREAD

**Issue by sfirke** [adamMaier/reviewr#3]
This commit: https://github.com/adamMaier/reviewr/commit/4230bbf673ef1c1b806e5dca576d69a758af5a52#diff-35ba4a2677442e210c23a00a5601aba3 undid your previous fix of reducing leading spaces in description text by making it all be on one line.  You'd implemented this fix as a result of https://github.com/r-lib/devtools/issues/1900.

I personally cannot replicate that devtools problem anymore with the error message `Found continuation line starting ...` - this repo installs okay for me as-is - but I just verified that Melissa gets this error message now, as indicated in devtools-1900.

**Comment by adamMaier** [comment]
Thanks, Sam. I deleted the leading spaces so Melissa can hopefully install the package. I couldn't replicate the issue either - I reinstalled reviewr after the latest commit -- but since this is a devtools issue that isn't surprising it would depend partly on set-up. Let me know if she still can't install after this fix.
